### ISSUE TITLE
Restructure README

### ISSUE THREAD

**Issue by tomyrd** [yetanotherco/aligned_layer_tendermint#40]
We should restructure the README after merging this. Maybe keeping the tutorial at the top in order of importance, and leaving the "How it works" section at the bottom.

_Originally posted by @JulianGCalderon in https://github.com/yetanotherco/aligned_layer_tendermint/pull/34#discussion_r1524851723_

**Comment by JulianGCalderon** [comment]
I was thinking the following layout (headings):

# Aligned Layer Blockchain

## Requeriments

software

## Example Local Blockchain

local serve and send example transactions

## Joining our Testnet

..

### Requeriments

software and local

### Node Setup

./setup_node.sh

### Creating an Account

Adding a key and requesting tokens from faucet

### Registering as a Validator

./setup_validator.sh

## Sending Proofs

Construction of proofs and verification

## How it Works

Theory and other tutorials, like local faucet.

**Comment by fborello-lambda** [comment]
LGTM
I would also add a section after `node validator setup` with some commands running transactions and querys. Maybe a Makefile or script can provide a better user experience.

**Comment by ManuelBilbao** [comment]
In "Join our Testnet", we should include both _automatic_ run with script and manual step by step

**Comment by JulianGCalderon** [comment]
> In "Join our Testnet", we should include both _automatic_ run with script and manual step by step

agreed

**Comment by JulianGCalderon** [comment]
Should we close this issue?

**Comment by ManuelBilbao** [comment]
I think we can, I've already done it
