### ISSUE TITLE
Upgrade server setup script

### ISSUE THREAD

**Issue by tomyrd** [yetanotherco/aligned_layer_tendermint#64]
There are manual operations we are doing to setup the servers. We should add them to the script:

- Update config files in blockchain-1 to enable the api for the explorer.
- The size of the server arrays is hardcoded in the for loops.
- Copy the files for the faucet.
- Add a flag to choose environment (default testing).

**Comment by JulianGCalderon** [comment]
I'd be good to move the binary to usr/local/bin and use it from there.

**Comment by JulianGCalderon** [comment]
completed by #73
